/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RetirementImport } from './routes/retirement'
import { Route as MoneyMapImport } from './routes/money-map'
import { Route as IncomeStatementImport } from './routes/income-statement'
import { Route as GoalsImport } from './routes/goals'
import { Route as BalanceSheetImport } from './routes/balance-sheet'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RetirementRoute = RetirementImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRoute,
} as any)

const MoneyMapRoute = MoneyMapImport.update({
  id: '/money-map',
  path: '/money-map',
  getParentRoute: () => rootRoute,
} as any)

const IncomeStatementRoute = IncomeStatementImport.update({
  id: '/income-statement',
  path: '/income-statement',
  getParentRoute: () => rootRoute,
} as any)

const GoalsRoute = GoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRoute,
} as any)

const BalanceSheetRoute = BalanceSheetImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/balance-sheet': {
      id: '/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof BalanceSheetImport
      parentRoute: typeof rootRoute
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsImport
      parentRoute: typeof rootRoute
    }
    '/income-statement': {
      id: '/income-statement'
      path: '/income-statement'
      fullPath: '/income-statement'
      preLoaderRoute: typeof IncomeStatementImport
      parentRoute: typeof rootRoute
    }
    '/money-map': {
      id: '/money-map'
      path: '/money-map'
      fullPath: '/money-map'
      preLoaderRoute: typeof MoneyMapImport
      parentRoute: typeof rootRoute
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/goals': typeof GoalsRoute
  '/income-statement': typeof IncomeStatementRoute
  '/money-map': typeof MoneyMapRoute
  '/retirement': typeof RetirementRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/goals': typeof GoalsRoute
  '/income-statement': typeof IncomeStatementRoute
  '/money-map': typeof MoneyMapRoute
  '/retirement': typeof RetirementRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/goals': typeof GoalsRoute
  '/income-statement': typeof IncomeStatementRoute
  '/money-map': typeof MoneyMapRoute
  '/retirement': typeof RetirementRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance-sheet'
    | '/goals'
    | '/income-statement'
    | '/money-map'
    | '/retirement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance-sheet'
    | '/goals'
    | '/income-statement'
    | '/money-map'
    | '/retirement'
  id:
    | '__root__'
    | '/'
    | '/balance-sheet'
    | '/goals'
    | '/income-statement'
    | '/money-map'
    | '/retirement'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceSheetRoute: typeof BalanceSheetRoute
  GoalsRoute: typeof GoalsRoute
  IncomeStatementRoute: typeof IncomeStatementRoute
  MoneyMapRoute: typeof MoneyMapRoute
  RetirementRoute: typeof RetirementRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceSheetRoute: BalanceSheetRoute,
  GoalsRoute: GoalsRoute,
  IncomeStatementRoute: IncomeStatementRoute,
  MoneyMapRoute: MoneyMapRoute,
  RetirementRoute: RetirementRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/balance-sheet",
        "/goals",
        "/income-statement",
        "/money-map",
        "/retirement"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/balance-sheet": {
      "filePath": "balance-sheet.tsx"
    },
    "/goals": {
      "filePath": "goals.tsx"
    },
    "/income-statement": {
      "filePath": "income-statement.tsx"
    },
    "/money-map": {
      "filePath": "money-map.tsx"
    },
    "/retirement": {
      "filePath": "retirement.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
